version: "3.4"

name: fastagency
services:
  fastapi-app:  # nosemgrep
    image: ghcr.io/${GITHUB_REPOSITORY}:${TAG}
    container_name: ${container_name}
    ports:
      - "8000:8000"
    environment:
      - DOMAIN=${DOMAIN}
      - DATABASE_URL=${DATABASE_URL}
      - PY_DATABASE_URL=${PY_DATABASE_URL}
      - AZURE_API_VERSION=${AZURE_API_VERSION}
      - AZURE_API_ENDPOINT=${AZURE_API_ENDPOINT}
      - AZURE_GPT35_MODEL=${AZURE_GPT35_MODEL}
      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - TOGETHER_API_KEY=${TOGETHER_API_KEY}
    networks:
      - fastagency

networks:
  fastagency:
    name: fastagency
