version: '3'

services:
  python-3.12:  # nosemgrep
    image: mcr.microsoft.com/devcontainers/python:3.12
    container_name: $USER-python-3.12-fastagency
    volumes:
      - ../../:/workspaces/fastagency:cached
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://admin:password@${USER}-postgres-py312-fastagency:5432/fastagency
      - PY_DATABASE_URL=postgresql://admin:password@${USER}-postgres-py312-fastagency:5432/pyfastagency
      - NATS_URL=nats://faststream:faststream_password@${USER}-nats-py312-fastagency:4222
    networks:
      - fastagency-network
  nats-fastagency:  # nosemgrep
    image: nats:latest
    container_name: $USER-nats-py312-fastagency
    # ports:
      # - "${PORT_PREFIX}4222:4222"
      # - "${PORT_PREFIX}9222:9222"
    env_file:
      - ../devcontainer.env
    volumes:
      - ../../examples/nats/server.conf:/etc/nats/server.conf
    command: [ "--config", "/etc/nats/server.conf" ]
    networks:
      - fastagency-network
  postgres-fastagency:  # nosemgrep
    image: postgres:latest
    container_name: $USER-postgres-py312-fastagency
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password  # pragma: allowlist secret
      POSTGRES_DB: fastagency
    # ports:
    #   - "${PORT_PREFIX}5432:5432"
    networks:
      - fastagency-network

networks:
  fastagency-network:
    name: "${USER}-fastagency-network"
