name: Cleanup Untagged Images

on:
  # every sunday at 00:00
  schedule:
    - cron: "0 0 * * SUN"
  # or manually
  workflow_dispatch:

jobs:
  delete-untagged-images:
    name: Delete Untagged Images
    runs-on: ubuntu-latest
    steps:
      - uses: bots-house/ghcr-delete-image-action@v1.1.0 # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
        with:
          # NOTE: at now only orgs is supported
          owner: airtai
          name: fastagency

          token: ${{ secrets.GITHUB_TOKEN }}
          # Keep latest N untagged images
          untagged-keep-latest: 1
      - uses: bots-house/ghcr-delete-image-action@v1.1.0 # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
        with:
          # NOTE: at now only orgs is supported
          owner: airtai
          name: fastagency-node

          token: ${{ secrets.GITHUB_TOKEN }}
          # Keep latest N untagged images
          untagged-keep-latest: 1
      - uses: bots-house/ghcr-delete-image-action@v1.1.0 # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
        with:
          # NOTE: at now only orgs is supported
          owner: airtai
          name: fastagency-auth-callout

          token: ${{ secrets.GITHUB_TOKEN }}
          # Keep latest N untagged images
          untagged-keep-latest: 1
